?start: _NL*  unit*
?unit: (h1)

h1: H1 _NL [_INDENT [source_about _NL]* block* _DEDENT] (h2)*
?source_about: AUTHOR | PUBLISHED | URL
AUTHOR.1: /@author:? / ANY       //著者
PUBLISHED.1: /@published:? / ANY // 第一出版日
URL.1: /@url:? / ANY

h2: H2 _NL [_INDENT block* _DEDENT] (h3)*
h3: H3 _NL [_INDENT block* _DEDENT] (h4)*
h4: H4 _NL [_INDENT block* _DEDENT] (h5)*
h5: H5 _NL [_INDENT block* _DEDENT] (h6)*
h6: H6 _NL [_INDENT block* _DEDENT]
HEAD: /[^#\n]+/
H1: "#" HEAD
H2: "##" HEAD
H3: "###" HEAD
H4: "####" HEAD
H5: "#####" HEAD
H6: "######" HEAD

?block: stmt [_INDENT (block|attach)+ _DEDENT]
?stmt:  (line|ctxline|COMMENT _NL)
?line: (ONELINE|MULTILINE|QUOTERM|DUPLICABLE) _NL
ctxline: ctype block

ANY: /[^\n]+/
COMMENT.1: "!" ANY

ONELINE: ANY
MULSEP: /\\\n[\t ]*/
MULTILINE: (ONELINE MULSEP)+ ONELINE
QUOTERM: /[ \t]/* "`" ANY "`"
DUPLICABLE: /[ \t]/* "+++" ANY "+++"

// 文脈
?ctype.2: (THUS|CAUSE|ANTONYM|EXAMPLE|GENERAL|REF|SIMILAR|BY|WHERE)
THUS.2:    "->"   // 故に
CAUSE.2:   "<-"   // なぜなら
ANTONYM.2: "<->"  // 対義関係
EXAMPLE.2: "ex." // 例化
GENERAL.2: "xe." // 汎化 例化の逆順
REF.2:     "ref."     // 引用
SIMILAR.2: "~="   // 類似
BY.2:      "by."       // アクターは誰
WHERE.2:   "where."

// 入れ子ではない付加情報
attach.3: (when) _NL
WHEN.2: "when."
TIME.2: ANY
?when.3: WHEN TIME

_NL: /(\r?\n[\t ]*)+/
%declare _INDENT _DEDENT
%import common.WS_INLINE
%import common.CNAME

%ignore COMMENT _NL
%ignore _NL COMMENT
